# Conda environment configuration for titan-project

name: titan_env

# Channels for conda to search for packages

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

# List of dependencies to install
dependencies:
  # Core conda packages
  - python=3.10        
  - pip                
  - pytorch            
  - torchvision        
  - torchaudio         
  # --- IMPORTANT ---
  # Specify the CUDA toolkit version compatible with your system and PyTorch.
  - pytorch-cuda=12.1

  # Dependencies to be installed via pip (from requirements.txt)
  - pip:
    - transformers>=4.36.0
    - datasets>=2.14.0
    - peft>=0.6.0
    # torch is handled by conda above
    - accelerate>=0.21.0
    - bitsandbytes>=0.41.0
    - trl>=0.7.2
    - wandb>=0.15.8
    - evaluate>=0.4.0
    - scipy>=1.11.0
    - scikit-learn>=1.3.0
    - PyYAML>=6.0.1
